# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'for_testUI_v3.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(860, 562)
        self.pushButton_predict = QtWidgets.QPushButton(Form)
        self.pushButton_predict.setGeometry(QtCore.QRect(730, 500, 121, 51))
        self.pushButton_predict.setObjectName("pushButton_predict")
        self.groupBox_model_choose = QtWidgets.QGroupBox(Form)
        self.groupBox_model_choose.setGeometry(QtCore.QRect(30, 30, 691, 181))
        self.groupBox_model_choose.setObjectName("groupBox_model_choose")
        self.lineEdit_r_model = QtWidgets.QLineEdit(self.groupBox_model_choose)
        self.lineEdit_r_model.setGeometry(QtCore.QRect(290, 100, 251, 31))
        self.lineEdit_r_model.setObjectName("lineEdit_r_model")
        self.toolButton_filedialog_h = QtWidgets.QToolButton(self.groupBox_model_choose)
        self.toolButton_filedialog_h.setGeometry(QtCore.QRect(540, 29, 91, 31))
        self.toolButton_filedialog_h.setObjectName("toolButton_filedialog_h")
        self.label_d = QtWidgets.QLabel(self.groupBox_model_choose)
        self.label_d.setGeometry(QtCore.QRect(160, 99, 81, 31))
        self.label_d.setObjectName("label_d")
        self.label_h = QtWidgets.QLabel(self.groupBox_model_choose)
        self.label_h.setGeometry(QtCore.QRect(160, 29, 81, 31))
        self.label_h.setObjectName("label_h")
        self.lineEdit_h_model = QtWidgets.QLineEdit(self.groupBox_model_choose)
        self.lineEdit_h_model.setGeometry(QtCore.QRect(290, 30, 251, 31))
        self.lineEdit_h_model.setObjectName("lineEdit_h_model")
        self.toolButton_filedialog_r = QtWidgets.QToolButton(self.groupBox_model_choose)
        self.toolButton_filedialog_r.setGeometry(QtCore.QRect(540, 99, 91, 31))
        self.toolButton_filedialog_r.setObjectName("toolButton_filedialog_r")
        self.toolButton_filedialog_h.raise_()
        self.label_d.raise_()
        self.label_h.raise_()
        self.lineEdit_h_model.raise_()
        self.toolButton_filedialog_r.raise_()
        self.lineEdit_r_model.raise_()
        self.groupBox_data_generate = QtWidgets.QGroupBox(Form)
        self.groupBox_data_generate.setGeometry(QtCore.QRect(30, 220, 691, 331))
        self.groupBox_data_generate.setObjectName("groupBox_data_generate")
        self.lineEdit_sample_n = QtWidgets.QLineEdit(self.groupBox_data_generate)
        self.lineEdit_sample_n.setGeometry(QtCore.QRect(290, 280, 71, 31))
        self.lineEdit_sample_n.setObjectName("lineEdit_sample_n")
        self.lineEdit_t_s = QtWidgets.QLineEdit(self.groupBox_data_generate)
        self.lineEdit_t_s.setGeometry(QtCore.QRect(290, 160, 71, 31))
        self.lineEdit_t_s.setObjectName("lineEdit_t_s")
        self.lineEdit_v_e = QtWidgets.QLineEdit(self.groupBox_data_generate)
        self.lineEdit_v_e.setGeometry(QtCore.QRect(290, 100, 71, 31))
        self.lineEdit_v_e.setObjectName("lineEdit_v_e")
        self.lineEdit_t_e = QtWidgets.QLineEdit(self.groupBox_data_generate)
        self.lineEdit_t_e.setGeometry(QtCore.QRect(290, 220, 71, 31))
        self.lineEdit_t_e.setObjectName("lineEdit_t_e")
        self.label_v_e = QtWidgets.QLabel(self.groupBox_data_generate)
        self.label_v_e.setGeometry(QtCore.QRect(160, 100, 121, 31))
        self.label_v_e.setObjectName("label_v_e")
        self.label_t_s = QtWidgets.QLabel(self.groupBox_data_generate)
        self.label_t_s.setGeometry(QtCore.QRect(160, 160, 121, 31))
        self.label_t_s.setObjectName("label_t_s")
        self.lineEdit_v_s = QtWidgets.QLineEdit(self.groupBox_data_generate)
        self.lineEdit_v_s.setGeometry(QtCore.QRect(290, 40, 71, 31))
        self.lineEdit_v_s.setObjectName("lineEdit_v_s")
        self.label_t_e = QtWidgets.QLabel(self.groupBox_data_generate)
        self.label_t_e.setGeometry(QtCore.QRect(160, 220, 121, 31))
        self.label_t_e.setObjectName("label_t_e")
        self.label_v_s = QtWidgets.QLabel(self.groupBox_data_generate)
        self.label_v_s.setGeometry(QtCore.QRect(160, 40, 121, 31))
        self.label_v_s.setObjectName("label_v_s")
        self.label_sample_n = QtWidgets.QLabel(self.groupBox_data_generate)
        self.label_sample_n.setGeometry(QtCore.QRect(160, 280, 121, 31))
        self.label_sample_n.setObjectName("label_sample_n")
        self.label_version = QtWidgets.QLabel(Form)
        self.label_version.setGeometry(QtCore.QRect(730, 40, 121, 81))
        self.label_version.setObjectName("label_version")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_predict.setText(_translate("Form", "Predict"))
        self.groupBox_model_choose.setTitle(_translate("Form", "Model Choose"))
        self.toolButton_filedialog_h.setText(_translate("Form", "Browse"))
        self.label_d.setText(_translate("Form", "Distance"))
        self.label_h.setText(_translate("Form", "Height"))
        self.toolButton_filedialog_r.setText(_translate("Form", "Browse"))
        self.groupBox_data_generate.setTitle(_translate("Form", "Data Generate"))
        self.label_v_e.setText(_translate("Form", "V End"))
        self.label_t_s.setText(_translate("Form", "Theta Start"))
        self.label_t_e.setText(_translate("Form", "Theta End"))
        self.label_v_s.setText(_translate("Form", "V Start"))
        self.label_sample_n.setText(_translate("Form", "# Sample"))
        self.label_version.setText(_translate("Form", "version"))
